name: Validate Poetry dependencies in Nixpkgs

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  check-python-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # So we can diff with base

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Get base branch pyproject.toml
        run: |
          git show origin/${{ github.base_ref }}:pyproject.toml > pyproject.base.toml

      - name: Check changed dependencies against Nixpkgs
        run: |
          pip install toml packaging
          python .github/scripts/check_nixpkgs_versions.py pyproject.base.toml pyproject.toml
